// Banco de perguntas do ABISSO.
//
// Formato de cada linha:  texto | letra obrigatória (ou vazio) | respostas, da mais comum para a menos comum
//
// A lista de respostas é o "modelo" de raridade: a posição na lista diz quão comum a resposta é para
// aquela pergunta (veja lib/estatisticas.ts). Respostas que NÃO estão na lista valem muito (são raras),
// desde que sejam palavras reais do português (lib/dicionario.ts). Os jogadores reais ajustam isso por cima.
//
// Para adicionar perguntas: acrescente SEMPRE no fim, em grupos de 7 (uma "semana" de perguntas),
// para não embaralhar os dias já jogados. Depois rode `npm run verificar`.

import { BANCO_NOVO } from "./banco-novo";

// Banco antigo (perguntas abertas): usado só no mergulho livre.
const BANCO = `
Uma fruta||banana,maçã,laranja,uva,morango,melancia,manga,abacaxi,mamão,limão,pera,melão,maracujá,goiaba,abacate,kiwi,pêssego,ameixa,cereja,coco,caju,acerola,jabuticaba,tangerina,mexerica,framboesa,amora,figo,caqui,lichia,romã,carambola,graviola,cupuaçu,açaí,pitaya,nectarina,damasco,mirtilo,cajá,pitanga,jaca,tamarindo,seriguela,umbu,tâmara,toranja,lima,groselha,bergamota,fruta-do-conde,jambo
Um animal de estimação||cachorro,gato,peixe,coelho,hamster,papagaio,tartaruga,passarinho,cavalo,porquinho-da-índia,calopsita,periquito,cobra,furão,galinha,pato,rato,canário,iguana,jabuti,lagarto,aranha,porco,ovelha,cabra,chinchila,coruja,sapo,camaleão,tarântula,pássaro,cachorrinho,gatinho,pinguim,macaco,pomba,tucano,boi,vaca,burro,lebre,esquilo,sagui,pônei,formiga,tigre,leão,galo,ganso
Uma cor||azul,vermelho,verde,amarelo,preto,branco,rosa,roxo,laranja,cinza,marrom,dourado,prata,bege,lilás,turquesa,violeta,vinho,ciano,magenta,salmão,creme,coral,carmim,anil,índigo,bordô,fúcsia,ocre,grená,lavanda,esmeralda,safira,rubi,âmbar,caramelo,mostarda,oliva,petróleo,areia,champanhe,nude,terracota,musgo,royal,cobre,bronze,ouro,marinho,púrpura
Um país||brasil,estados unidos,argentina,portugal,frança,japão,itália,alemanha,espanha,china,canadá,méxico,inglaterra,chile,rússia,índia,austrália,uruguai,colômbia,peru,paraguai,bolívia,venezuela,equador,cuba,suíça,holanda,bélgica,suécia,noruega,grécia,turquia,egito,áfrica do sul,coreia do sul,tailândia,irlanda,dinamarca,polônia,nigéria,marrocos,israel,angola,moçambique,arábia saudita,finlândia,áustria,croácia,ucrânia,escócia,nova zelândia,indonésia
Uma profissão||médico,professor,advogado,engenheiro,policial,enfermeiro,motorista,programador,dentista,arquiteto,psicólogo,padeiro,cozinheiro,pedreiro,bombeiro,piloto,jornalista,contador,veterinário,cabeleireiro,eletricista,encanador,pintor,fotógrafo,músico,ator,cantor,escritor,garçom,vendedor,secretária,administrador,médica,professora,farmacêutico,fisioterapeuta,nutricionista,designer,mecânico,agricultor,carpinteiro,artista,juiz,delegado,militar,cientista,empresário,jogador,atleta,chef,personal trainer
Algo que se encontra na geladeira||leite,ovo,queijo,água,manteiga,iogurte,suco,refrigerante,presunto,carne,frango,legumes,verduras,fruta,margarina,cerveja,maionese,ketchup,mostarda,requeijão,molho,sobra de comida,tomate,alface,cenoura,batata,mamão,melancia,pudim,gelatina,sorvete,bolo,pizza,sobremesa,peixe,linguiça,salsicha,mussarela,suco de laranja,bebida,tempero,geleia,doce de leite,chocolate,vinho,comida,marmita,pão,leite condensado,creme de leite
Algo que você leva para a praia||protetor solar,toalha,guarda-sol,cadeira,óculos de sol,chinelo,biquíni,água,canga,boné,chapéu,bolsa,cooler,isopor,sunga,bola,raquete,prancha,barraca,esteira,bronzeador,celular,snorkel,balde,pazinha,comida,bebida,cerveja,sanduíche,roupa de banho,protetor labial,tapete,livro,fone de ouvido,caixa de som,frescobol,boia,coco,sacola,dinheiro
Um instrumento musical||violão,piano,guitarra,bateria,flauta,violino,saxofone,sanfona,trompete,baixo,teclado,pandeiro,cavaquinho,harpa,violoncelo,clarinete,tambor,acordeão,ukulele,gaita,trombone,tuba,berimbau,atabaque,triângulo,surdo,viola,órgão,xilofone,oboé,fagote,flauta doce,reco-reco,cuíca,zabumba,bongô,maracas,cajon,banjo,bandolim,harmônica,contrabaixo,percussão,sintetizador,gaita de foles,didgeridoo,ocarina,tamborim,agogô,carrilhão
Um esporte||futebol,vôlei,basquete,natação,tênis,judô,corrida,handebol,ginástica,atletismo,boxe,surfe,skate,ciclismo,karatê,capoeira,rugby,golfe,beisebol,futsal,hóquei,esgrima,remo,tênis de mesa,vôlei de praia,jiu-jitsu,muay thai,xadrez,musculação,pilates,crossfit,patinação,escalada,arco e flecha,triatlo,maratona,polo aquático,badminton,paraquedismo,hipismo,automobilismo,fórmula 1,mma,taekwondo,lutas,caminhada,yoga,dança,sinuca,boliche,futevôlei
Um prato brasileiro||feijoada,arroz com feijão,moqueca,churrasco,coxinha,acarajé,baião de dois,farofa,pão de queijo,strogonoff,brigadeiro,vatapá,pastel,tapioca,cuscuz,galinhada,feijão tropeiro,escondidinho,picanha,lasanha,bobó de camarão,caruru,tutu de feijão,vaca atolada,carne de sol,pirão,mocotó,rabada,sarapatel,tacacá,pato no tucupi,maniçoba,cuscuz paulista,virado à paulista,bolinho de bacalhau,empadão,joelho,esfiha,kibe,pamonha,canjica,bife à parmegiana,frango com quiabo,peixada,sururu,buchada,galeto,costela,linguiça,feijão com arroz
Uma cidade brasileira||são paulo,rio de janeiro,salvador,brasília,fortaleza,curitiba,recife,belo horizonte,porto alegre,manaus,belém,goiânia,florianópolis,vitória,natal,maceió,joão pessoa,campinas,santos,são luís,campo grande,cuiabá,teresina,aracaju,macapá,porto velho,boa vista,palmas,rio branco,niterói,guarulhos,ribeirão preto,uberlândia,londrina,joinville,blumenau,gramado,foz do iguaçu,paraty,búzios,ouro preto,petrópolis,olinda,porto seguro,bonito,jericoacoara,fernando de noronha,sorocaba,juiz de fora,caxias do sul
Um super-herói||batman,homem-aranha,super-homem,homem de ferro,mulher-maravilha,hulk,thor,capitão américa,flash,aquaman,pantera negra,doutor estranho,homem-formiga,viúva negra,wolverine,deadpool,lanterna verde,ciborgue,superman,capitã marvel,gavião arqueiro,visão,feiticeira escarlate,ciclope,tempestade,superboy,batgirl,robin,mulher-gato,demolidor,justiceiro,motoqueiro fantasma,quarteto fantástico,x-men,capitão marvel,tocha humana,groot,rocket,shazam,hellboy,spawn,kick-ass,incrível hulk,mulher-aranha,supergirl,ravena,mulher-hulk,ben 10,he-man
Um doce||brigadeiro,chocolate,pudim,beijinho,sorvete,bolo,pavê,paçoca,goiabada,doce de leite,cocada,quindim,brownie,torta,mousse,pirulito,bala,chiclete,bombom,pé de moleque,rapadura,romeu e julieta,maria-mole,algodão doce,sonho,churros,trufa,cupcake,donut,panqueca,gelatina,curau,canjica,cajuzinho,olho de sogra,bem casado,maçã do amor,suspiro,manjar,arroz doce,rabanada,pão de mel,mel,geleia,marshmallow,tiramisu,macaron,cheesecake,petit gâteau,picolé
Um meio de transporte||carro,ônibus,avião,bicicleta,metrô,trem,moto,barco,navio,caminhão,helicóptero,táxi,uber,patinete,skate,van,balsa,lancha,bonde,teleférico,jipe,carroça,cavalo,trator,foguete,submarino,jet ski,triciclo,patins,kombi,ambulância,carruagem,jangada,canoa,hoverboard,trólebus,monociclo,carro de boi,elevador,escada rolante,burro,camelo,riquixá,balão,dirigível,mototáxi,esteira
Um móvel da casa||sofá,cama,mesa,cadeira,guarda-roupa,estante,armário,poltrona,cômoda,escrivaninha,rack,criado-mudo,beliche,penteadeira,sapateira,aparador,buffet,banco,banqueta,puff,baú,prateleira,mesa de centro,mesa de jantar,balcão,bancada,berço,cabideiro,espelho,painel,biombo,cristaleira,colchão,rede,escada,mesinha,gaveteiro,arquivo,sofá-cama,divã,namoradeira,cadeira de balanço,cabeceira,nicho,louceiro,adega,vitrine,tapete,cortina,luminária
Uma flor||rosa,girassol,margarida,tulipa,orquídea,lírio,violeta,jasmim,cravo,lavanda,camélia,hortênsia,gérbera,begônia,azaleia,crisântemo,narciso,papoula,lótus,dália,gardênia,amor-perfeito,petúnia,magnólia,copo-de-leite,bromélia,antúrio,íris,peônia,ipê,flor de lótus,flor de cerejeira,acácia,malmequer,onze-horas,alecrim,mimosa,primavera,boca-de-leão,cosmos,flamboyant,hibisco,verbena,zínia,flor-de-liz
Um mês do ano||dezembro,janeiro,junho,julho,março,maio,setembro,abril,outubro,novembro,agosto,fevereiro
Um personagem de desenho animado||mickey,bob esponja,pato donald,tom e jerry,pateta,homer simpson,scooby-doo,pica-pau,mônica,cebolinha,magali,cascão,bugs bunny,patolino,pernalonga,minnie,tom,jerry,tio patinhas,popeye,pluto,garfield,snoopy,charlie brown,fred flintstone,tartaruga ninja,pikachu,naruto,goku,shrek,woody,buzz lightyear,nemo,dory,simba,elsa,anna,olaf,moana,patrick,lula molusco,sr. sirigueijo,bart simpson,peppa pig,ben 10,piu-piu,coiote,papa-léguas,pinky e cérebro
Uma matéria da escola||matemática,português,história,geografia,ciências,educação física,inglês,biologia,química,física,artes,filosofia,sociologia,literatura,redação,religião,música,espanhol,informática,gramática,educação artística,álgebra,geometria,desenho,ensino religioso,robótica,economia,empreendedorismo,teatro,francês,latim,história do brasil,estatística,trigonometria,orientação,educação financeira,projeto de vida,produção de texto,leitura,ortografia,alfabetização,tabuada,cálculo,ética,cidadania,política
Algo que faz barulho||trovão,buzina,sirene,despertador,cachorro,telefone,motor,campainha,martelo,liquidificador,furadeira,moto,avião,trem,fogos de artifício,tambor,bateria,trovoada,grito,música,carro,helicóptero,ônibus,britadeira,alarme,rádio,televisão,vento,chuva,mar,onda,festa,criança,bebê,sino,apito,aplauso,porta,motosserra,serra,cortador de grama,aspirador,secador,máquina de lavar,ventilador,ar condicionado,geladeira,explosão,tiro,galo
Uma ferramenta||martelo,chave de fenda,alicate,serra,furadeira,chave inglesa,trena,pá,enxada,parafusadeira,lixa,formão,plaina,esquadro,nível,serrote,picareta,machado,foice,rastelo,tesoura,pincel,rolo,espátula,torquês,grampo,morsa,broca,chave allen,chave de boca,marreta,martelete,esmerilhadeira,lima,cinzel,prumo,carrinho de mão,escada,tesoura de poda,facão,alavanca,pé de cabra,estilete,mangueira,pistola de cola,solda,soldador,multímetro,caixa de ferramentas,prego
Uma fruta tropical||manga,abacaxi,maracujá,coco,mamão,goiaba,caju,açaí,banana,graviola,jaca,cupuaçu,carambola,pitanga,acerola,cajá,melancia,caqui,abacate,lichia,pitaya,jabuticaba,seriguela,tamarindo,umbu,fruta-pão,rambutan,durian,mangostão,jambo,sapoti,bacuri,buriti,pupunha,tucumã,murici,araçá,cambuci,laranja,fruta-do-conde,banana-da-terra,melão,uva,limão,kiwi,morango,pêssego,figo
Um objeto redondo||bola,roda,moeda,prato,relógio,lua,pizza,disco,pneu,globo,planeta,sol,bexiga,balão,anel,aro,bolinha,esfera,círculo,volante,botão,tampa,tambor,bola de futebol,bola de basquete,bola de gude,miçanga,ovo,laranja,pulseira,cd,dvd,espelho,mesa,panela,bandeja,rosquinha,donut,bola de tênis,pião,ioiô,arco,bambolê,boia,lente,olho,cabeça,terra,rolo,bacia
Algo que voa||avião,pássaro,helicóptero,borboleta,drone,balão,abelha,foguete,pipa,mosca,mosquito,morcego,águia,pombo,papagaio,passarinho,beija-flor,coruja,ave,aeronave,planador,asa-delta,paraquedas,disco voador,ovni,satélite,vassoura,super-herói,superman,libélula,vespa,gafanhoto,besouro,joaninha,marimbondo,urubu,gavião,falcão,cegonha,pelicano,gaivota,andorinha,tucano,arara,dragão,fada,nuvem,folha,poeira
Algo que você faz antes de dormir||escovar os dentes,ler,orar,tomar banho,mexer no celular,assistir tv,apagar a luz,beber água,rezar,meditar,pensar,trocar de roupa,deitar,fechar a porta,ouvir música,alongar,passar creme,lavar o rosto,ver série,assistir netflix,conversar,jantar,fazer xixi,desligar o celular,carregar o celular,colocar o pijama,arrumar a cama,programar o despertador,planejar o dia,agradecer,escrever,escrever no diário,tomar chá,tomar leite,abraçar,dar boa noite,namorar,usar o fio dental,fechar as cortinas,respirar fundo,contar carneirinhos,desligar a tv,rever o dia,ver vídeos,ver instagram,ler a bíblia,cantar
Um animal marinho||tubarão,golfinho,baleia,polvo,tartaruga,peixe,água-viva,estrela-do-mar,caranguejo,foca,leão-marinho,lula,camarão,ouriço-do-mar,cavalo-marinho,orca,raia,arraia,moreia,lagosta,siri,ostra,mexilhão,concha,pinguim,enguia,peixe-palhaço,medusa,anêmona,coral,baiacu,atum,sardinha,salmão,bacalhau,robalo,garoupa,linguado,peixe-espada,peixe-boi,morsa,krill,plâncton,esponja,caramujo,cachalote,narval,bagre
Um lugar para passar as férias||praia,fazenda,disney,paris,europa,serra,sítio,nordeste,resort,cruzeiro,camping,acampamento,montanha,orlando,miami,nova york,londres,roma,lisboa,cancún,gramado,campos do jordão,florianópolis,rio de janeiro,salvador,fortaleza,porto de galinhas,maceió,natal,jericoacoara,fernando de noronha,bonito,foz do iguaçu,buenos aires,santiago,patagônia,caribe,bahamas,havaí,maldivas,bali,tailândia,japão,egito,casa da vovó,casa de praia,chácara,ilha,lago
Algo azul||céu,mar,oceano,água,jeans,piscina,safira,bandeira,blusa,carro,baleia,lago,rio,smurf,sonic,stitch,dory,azulão,papagaio,arara,pássaro,mirtilo,hortênsia,uniforme,lápis,caneta,tinta,olho,camisa,calça,tênis,cobalto,turquesa,marinho,lápis-lazuli,tanzanita,vestido,facebook,twitter,tela,ar,gelo,neve
Algo gelado||sorvete,gelo,picolé,água,cerveja,neve,geladeira,freezer,refrigerante,suco,vento,inverno,iceberg,geleira,pinguim,milkshake,açaí,gelatina,granizo,ar condicionado,polo norte,antártida,cubo de gelo,água gelada,coca-cola,pista de gelo,iglu,boneco de neve,congelador,sobremesa,chope,vodka,mão,pé,coração,noite,banho,sala,café gelado,chá gelado,limonada,raspadinha,frozen,esquimó,urso polar,pedra de gelo,gelo seco,chuva,orvalho
Um tipo de massa||macarrão,lasanha,espaguete,nhoque,pizza,pastel,ravióli,penne,talharim,fettuccine,macarronada,parafuso,fusilli,capelete,rondelli,canelone,tortellini,farfalle,gravatinha,miojo,massa folhada,massa de bolo,massa de pizza,massa de pastel,massa fresca,massa caseira,linguine,rigatoni,conchiglie,spaghetti,yakisoba,udon,soba,tagliatelle,macarrão instantâneo,macarrão de arroz,massa de pão,massa de tapioca,massa de panqueca,pão,bolo,empada,esfiha,calzone,crepe,panqueca,pierogi,massa podre,massa choux
Um animal que começa com C|C|cachorro,cavalo,cobra,coelho,camelo,canguru,crocodilo,cabra,camaleão,capivara,cervo,chimpanzé,coruja,cisne,cegonha,caranguejo,coala,cotia,carneiro,corvo,canário,cachalote,castor,cutia,calopsita,cigarra,centopeia,caracol,camarão,cascavel,cágado,caititu,condor,codorna,coiote,carcará,caturrita
Um animal que começa com B|B|boi,baleia,borboleta,búfalo,besouro,bode,bem-te-vi,barata,bicho-preguiça,bezerro,bisão,babuíno,bagre,baiacu,beija-flor,burro,bulldog,borrego,bonobo,boto,brontossauro,bacalhau,bicho-da-seda,bicho-pau,boxer,beagle,bernese,bonito,búfalo-d'água
Um animal que começa com G|G|gato,galinha,girafa,gorila,golfinho,gavião,galo,gambá,ganso,gafanhoto,gaivota,guaxinim,guepardo,gazela,gnu,golden retriever,gato-do-mato,gaio,garça,gralha,grilo,garoupa,guará,gamo,geco,gavião-real,gato siamês,gorgulho,guaiamum
Um animal que começa com P|P|pato,porco,papagaio,pinguim,peixe,pássaro,pantera,panda,pavão,pombo,polvo,pônei,pulga,piolho,perereca,pernilongo,pitbull,poodle,pug,preguiça,puma,porco-espinho,porquinho,peru,perdiz,pelicano,pardal,periquito,piranha,pirarucu,pacu,pintado,pintinho,pastor alemão,pinscher
Uma fruta que começa com M|M|maçã,manga,morango,melancia,mamão,melão,maracujá,mexerica,mirtilo,mangaba,mangostão,marmelo,murici,macadâmia,mamão papaia,maçã verde,maçã fuji,mandarina,mamey,maracujá-doce
Uma fruta que começa com L|L|laranja,limão,lichia,lima,limão-siciliano,limão-taiti,laranja-pera,laranja-bahia,laranja-lima,lúcuma,longan,lima-da-pérsia
Um país que começa com A|A|argentina,alemanha,austrália,áustria,angola,arábia saudita,albânia,argélia,afeganistão,armênia,azerbaijão,andorra,áfrica do sul,américa,antártida,aruba
Um país que começa com P|P|portugal,peru,paraguai,polônia,panamá,paquistão,palestina,porto rico,países baixos,papua-nova guiné,palau,polinésia
Uma cidade que começa com S|S|são paulo,salvador,santos,são luís,santiago,sydney,seul,são josé,sorocaba,santo andré,são bernardo do campo,são josé dos campos,são vicente,sobral,sinop,sapucaia do sul,santa maria,santarém,saquarema,sevilha,singapura,salzburgo,são petersburgo,são francisco,san diego,seattle,suzano,sumaré,serra,salto,sete lagoas,são carlos,são leopoldo,são gonçalo,são joão del rei
Uma comida que começa com P|P|pizza,pão,pastel,pipoca,pudim,peixe,panqueca,pamonha,pão de queijo,picanha,purê,pastelão,paçoca,pirão,pernil,presunto,peru,pato,pimentão,pepino,pêssego,pera,pão de batata,pão de forma,pão francês,pão de mel,pudim de leite,paella,pad thai,parmegiana,polenta,pinhão,pacu,pirarucu
Uma comida que começa com B|B|batata,bolo,bife,bolacha,brigadeiro,baião de dois,biscoito,banana,bacon,bacalhau,beterraba,berinjela,brócolis,bombom,bobó,brownie,burrito,bruschetta,batata frita,batata doce,bife à parmegiana,bolo de cenoura,bolo de chocolate,bolinho de chuva,bolinho de bacalhau,bala,baguete,bagel,bauru,beijinho,bomba de chocolate,bolo de fubá,bolacha de maisena,bisteca,bacuri,biju,bem casado
Um nome de mulher que começa com M|M|maria,mariana,marcela,mariah,marta,mônica,maitê,manuela,mayara,melissa,michele,milena,marina,mirian,monique,marisa,márcia,mara,maísa,maria clara,maria eduarda,maria luiza,mirella,mel,morgana,marília,marlene,mercedes,madalena,margarida,mariza,mylena,micaela,mia,magda,marli,matilde,mirtes,mayra,mabel
Um nome de homem que começa com J|J|joão,josé,jorge,júlio,jonas,juliano,jefferson,jaime,jair,jean,jonathan,jhonatan,jeferson,josué,joaquim,julio cesar,jorginho,jackson,jacó,jeremias,jesus,jhon,jonatas,judas,júnior,juvenal,jânio,jota,jordan
Um objeto que começa com C|C|cadeira,caneta,copo,celular,carro,caderno,chave,computador,caixa,cama,cadeado,câmera,calculadora,carteira,cinto,chinelo,colher,cabide,cesta,cortina,controle remoto,cofre,corda,cola,compasso,carregador,capacete,coberta,colar,caneca,cesto,cavalete,cinzeiro,cachimbo,cartão,carta,catálogo,chapéu,camisa,calça,casaco,cueca,cano,corrente,cadeirinha,cabo,capa,cédula,cofrinho
Um objeto que começa com T|T|telefone,televisão,tesoura,tênis,taça,tigela,toalha,tapete,tela,teclado,tinta,tubo,tábua,talher,tampa,tambor,travesseiro,termômetro,tampão,trena,tijolo,tocha,tomada,torneira,trave,troféu,tripé,trombeta,tesourinha,tabuleiro,tabela,tanque,telhado,tenda,tinteiro
Algo da cozinha que começa com F|F|fogão,faca,forno,frigideira,freezer,fruteira,filtro,fósforo,forma,faqueiro,fatiador,fervedor,funil,fôrma de bolo,fritadeira,forno elétrico,forno de micro-ondas,fogareiro,faca de pão,fruta,feijão,farinha,fermento,fubá,frango,fígado,fatia,fritura,feijoada,filé,fondue,frios
Uma profissão que começa com P|P|professor,policial,pedreiro,padeiro,pintor,piloto,psicólogo,programador,pizzaiolo,pescador,psiquiatra,promotor,personal trainer,paisagista,pastor,padre,presidente,político,publicitário,pedagogo,pediatra,perito,porteiro,produtor,palhaço,pesquisador,podólogo,policial militar,policial federal,professora,pintora,padeira,paramédico,piloto de avião,piloto de corrida,planejador,perfumista,pedicure,poeta,paleontólogo,parteira,pianista,patrulheiro
Uma coisa que você faz no domingo||dormir,almoçar,descansar,assistir tv,churrasco,ir à igreja,passear,ver futebol,ficar em casa,ler,cozinhar,limpar a casa,sair,ir ao shopping,ir à praia,visitar a família,jogar bola,fazer nada,assistir filme,ver série,ir ao parque,arrumar a casa,lavar roupa,planejar a semana,relaxar,dormir até tarde,tomar café da manhã,ir ao cinema,fazer compras,jogar videogame,dançar,acordar tarde,orar,rezar,ir à missa,fazer feira,almoço em família,pedalar,correr,caminhar,estudar,trabalhar,pescar,tomar sol,jogar cartas,ouvir música,tirar soneca,beber,pedir pizza,visitar a vó
Algo que se paga todo mês||aluguel,conta de luz,água,internet,cartão,condomínio,celular,escola,financiamento,luz,gás,telefone,plano de saúde,iptu,faculdade,mensalidade,academia,netflix,spotify,seguro,parcela,empréstimo,prestação,imposto,streaming,tv a cabo,mercado,supermercado,carro,seguro do carro,ipva,cartão de crédito,dívida,assinatura,boleto,fatura,conta,pensão,transporte,combustível,gasolina,lazer,remédio,babá,empregada,diarista,cursinho,inglês,natação,colégio
Uma série ou novela||friends,breaking bad,casa de papel,stranger things,game of thrones,avenida brasil,rebelde,the office,round 6,grey's anatomy,the walking dead,vikings,peaky blinders,la casa de papel,the crown,big bang theory,how i met your mother,sex education,riverdale,euphoria,the last of us,wandinha,bridgerton,dark,black mirror,prison break,lost,house,supernatural,suits,narcos,chaves,malhação,carrossel,mulheres apaixonadas,senhora do destino,o clone,pantanal,cheias de charme,vale tudo,roque santeiro,a favorita,páginas da vida,laços de família,fina estampa,império,amor de mãe,travessia,renascer,terra e paixão,mar do sertão
Uma emoção||alegria,tristeza,raiva,medo,amor,ansiedade,saudade,felicidade,ódio,surpresa,nojo,angústia,paixão,ciúme,inveja,culpa,vergonha,esperança,empolgação,euforia,tédio,frustração,solidão,confusão,orgulho,gratidão,compaixão,empatia,desespero,pânico,preocupação,alívio,nostalgia,decepção,melancolia,entusiasmo,curiosidade,calma,paz,serenidade,desânimo,irritação,estresse,pavor,fúria,êxtase,afeto,carinho
Algo que cheira bem||perfume,flor,café,pão,bolo,rosa,chuva,lavanda,comida,bebê,jasmim,baunilha,churrasco,pipoca,chocolate,sabonete,shampoo,amaciante,mato,terra molhada,grama,mar,praia,incenso,vela,canela,laranja,limão,fruta,maçã,morango,pão de queijo,pão quentinho,café coado,bolo no forno,roupa limpa,roupa lavada,cabelo,pele,madeira,eucalipto,hortelã,manjericão,alecrim,cravo,lírio,sândalo,óleo,perfumaria
Algo que você perde sempre||chave,celular,controle remoto,óculos,carteira,tempo,paciência,meia,guarda-chuva,carregador,caneta,fone de ouvido,dinheiro,isqueiro,documento,cartão,jogo,esperança,sono,tampa,brinco,anel,relógio,lápis,borracha,boné,bolsa,livro,controle,mouse,pendrive,senha,hora,ônibus,fôlego,foco,juízo,cabeça,memória,vontade,peso,cabelo,calma,voz,rumo,time,partida
Um lugar da escola||sala de aula,cantina,pátio,biblioteca,quadra,laboratório,diretoria,banheiro,secretaria,refeitório,corredor,auditório,sala dos professores,coordenação,recreio,portaria,estacionamento,sala de informática,sala de música,sala de artes,ginásio,piscina,horta,playground,jardim,enfermaria,almoxarifado,cozinha,sala de vídeo,sala de leitura,sala de reunião,lanchonete,bebedouro,escada,mural,sala de ciências,sala de dança,campo,arquibancada,entrada,saída,portão,fila,lousa,carteira,armário,mesa,cadeira,pátio coberto,biblioteca escolar
Uma bebida quente||café,chá,chocolate quente,leite,cappuccino,chimarrão,caldo,vinho quente,quentão,café com leite,leite quente,chá de camomila,chá de hortelã,chá mate,mate,latte,expresso,café expresso,capuccino,mocaccino,caldo de feijão,sopa,gengibre,chá de gengibre,chá preto,chá verde,chá de erva-doce,chá de boldo,chá de cidreira,leite com chocolate,achocolatado,toddy,nescau,ovomaltine,conhaque,grog,cachaça com mel,água quente,limão com mel,chai,matcha,café coado,café preto,cafezinho,bebida quente,vinho,cidra,sidra
Uma bebida||água,suco,refrigerante,cerveja,café,vinho,leite,chá,coca-cola,cachaça,caipirinha,vodka,whisky,energético,guaraná,suco de laranja,limonada,água de coco,milkshake,vitamina,chopp,champanhe,tequila,gin,rum,licor,sidra,smoothie,isotônico,gatorade,red bull,fanta,sprite,pepsi,mate,chimarrão,caldo de cana,batida,cerveja gelada,drink,coquetel,soda,água mineral,água com gás,kombucha,leite de soja,suco de uva,suco de maçã,kefir,aguardente,uísque
Um aplicativo no celular||whatsapp,instagram,tiktok,youtube,facebook,uber,spotify,netflix,twitter,telegram,gmail,google maps,waze,ifood,mercado livre,shopee,amazon,nubank,pix,câmera,galeria,calculadora,relógio,calendário,notas,mensagens,telefone,chrome,safari,snapchat,pinterest,linkedin,discord,twitch,duolingo,tinder,bumble,rappi,shein,aliexpress,kwai,pokémon go,candy crush,free fire,roblox,minecraft
Algo que você faz no verão||praia,sorvete,piscina,viajar,churrasco,suar,tomar sol,nadar,tomar água,tomar banho,ir à praia,beber,tomar cerveja,tomar sorvete,passear,acampar,pescar,pedalar,correr,tomar suco,comer melancia,usar short,usar chinelo,ficar de férias,descansar,dormir,reunir os amigos,fazer piquenique,jogar vôlei,ir ao parque,ir ao clube,usar protetor solar,bronzear,surfar,mergulhar,tomar banho de mangueira,ir à cachoeira,ir ao rio,dormir com ventilador,ligar o ar condicionado,tomar picolé,andar de bicicleta,fazer trilha,brincar,sair à noite,festas,carnaval,reveillon,natal,ano novo
Um planeta ou astro||terra,sol,lua,marte,júpiter,saturno,vênus,netuno,urano,mercúrio,plutão,estrela,cometa,asteroide,galáxia,via láctea,sírius,alfa centauri,proxima centauri,andrômeda,órion,cruzeiro do sul,buraco negro,nebulosa,supernova,meteoro,meteorito,satélite,lua cheia,ceres,eris,europa,titã,io,ganimedes,calisto,fobos,deimos,tritão,caronte,betelgeuse,polaris,estrela d'alva,estrela polar,sistema solar,universo,cosmos,espaço
Uma parte do corpo||mão,cabeça,pé,olho,braço,perna,coração,nariz,boca,orelha,dedo,joelho,cotovelo,ombro,pescoço,costas,barriga,peito,cabelo,dente,língua,cérebro,pulmão,fígado,estômago,rim,osso,pele,unha,tornozelo,calcanhar,coxa,panturrilha,quadril,cintura,testa,sobrancelha,cílio,queixo,bochecha,garganta,axila,punho,palma,polegar,intestino,músculo,veia,sangue,umbigo
Um país da América do Sul||brasil,argentina,chile,colômbia,peru,uruguai,paraguai,venezuela,bolívia,equador,guiana,suriname,guiana francesa,falkland,malvinas
Algo que você leva na mochila||caderno,caneta,estojo,garrafa,celular,carregador,livro,lápis,carteira,chave,fone de ouvido,casaco,guarda-chuva,lanche,água,notebook,tablet,borracha,régua,apontador,lancheira,marmita,dinheiro,documento,remédio,óculos,boné,toalha,roupa,tênis,maquiagem,perfume,desodorante,escova de dente,pente,absorvente,power bank,pendrive,cadeado,cartão,passaporte,máquina fotográfica,câmera,lupa,mapa,bússola,canivete,lanterna,cantil,pilha
Algo que você faz com as mãos||escrever,digitar,aplaudir,cozinhar,tocar,segurar,desenhar,lavar,pegar,comer,pintar,abraçar,cumprimentar,bater palmas,costurar,tricotar,carregar,levantar,empurrar,puxar,jogar,arremessar,lançar,acenar,apontar,apertar,massagear,tocar piano,tocar violão,fazer carinho,dar tchau,fazer sinais,fazer gestos,fazer artesanato,fazer comida,limpar,arrumar,pentear,passar,dobrar,amarrar,abrir,fechar,rasgar,cortar,esculpir,modelar,jogar bola,dirigir,trabalhar
Um jogo de tabuleiro||xadrez,banco imobiliário,dama,war,detetive,imagem e ação,ludo,scrabble,gamão,jogo da vida,uno,monopoly,cara a cara,cluedo,dominó,batalha naval,trilha,catan,risk,pandemic,carcassonne,dixit,ticket to ride,jenga,twister,lig 4,resta um,quebra-cabeça,go,mancala,tapa certo,perfil,master,palavras cruzadas,cilada,jogo da velha,bingo,loto,palavra secreta,pega varetas,ludo real,bang,codenames,azul,splendor,gloomhaven,dobble
Um nome de cachorro||rex,thor,bob,toby,pipoca,mel,bolinha,luna,nina,max,belinha,fofo,rambo,princesa,tobby,lilica,fred,amora,lady,bidu,floquinho,pretinho,scooby,costelinha,dengo,bento,zeus,simba,sansão,billy,mia,belle,lola,cacau,pandora,tigre,duque,mimi,zé,pingo,fiel,bolota,catarina,pantufa,farofa,feijão,paçoca,churros,bolacha,biscoito,nuvem,neve,toddy,mike
Um nome de gato||mingau,tom,garfield,félix,mia,nina,gatinho,simba,mimi,frajola,miau,bolinha,princesa,luna,mel,pipoca,tigre,leo,ruivo,mimosa,tico,gata,bichano,bola de neve,sushi,pantera,cinza,nikita,amora,lilica,felícia,frida,chico,bichana,rabito,bigode,pelúcia,algodão,fofinho,jujuba,biscoito,peludo
Um animal da fazenda||vaca,cavalo,porco,galinha,boi,ovelha,cabra,pato,galo,burro,jumento,peru,ganso,coelho,bode,bezerro,pintinho,cachorro,gato,égua,potro,touro,carneiro,mula,jegue,búfalo,pônei,codorna,faisão,pavão,porquinho,marreco,cordeiro,leitão,lhama,avestruz,abelha,minhoca,cão,coruja,rato,pomba,pardal,ratinho,capivara,tatu,cavalinho,galinha d'angola,guiné
Algo que acontece em uma festa||música,dança,bolo,bebida,conversa,brinde,parabéns,bagunça,comida,risada,diversão,bebedeira,encontro,sorteio,jogos,brincadeira,fotos,abraço,cantoria,karaokê,gritaria,aglomeração,briga,paquera,beijo,namoro,fofoca,discurso,presente,decoração,fogos,balão,churrasco,pizza,dj,bar,balada,pista,luz,som,convidados,amigos,família,alegria,sorrisos,vômito,ressaca,festança
Um tipo de clima||chuva,sol,frio,calor,vento,neve,neblina,tempestade,tropical,temperado,equatorial,árido,semiárido,subtropical,polar,desértico,mediterrâneo,continental,oceânico,úmido,seco,nublado,ensolarado,garoa,trovoada,granizo,geada,umidade,mormaço,furacão,tornado,ciclone,nevasca,seca,orvalho,céu limpo,céu azul,tempo bom,tempo ruim,tufão,monção,temporal,aguaceiro,cerração,brisa,friagem,onda de calor,abafado,chuvoso,ventania
Um superpoder||voar,invisibilidade,super força,telepatia,velocidade,ler mentes,teletransporte,viajar no tempo,ficar invisível,força,superforça,super velocidade,telecinese,regeneração,controlar o tempo,parar o tempo,invisível,flutuar,visão de raio x,raio laser,fogo,gelo,eletricidade,controlar a água,controlar o fogo,elasticidade,imortalidade,cura,clarividência,hipnose,ilusão,metamorfose,mudar de forma,super audição,super visão,visão noturna,escalar paredes,respirar debaixo d'água,falar com animais,super inteligência,magia,levitação,clonagem,sobrevivência,nadar,corrida,pular alto,soltar teia,teia
Algo que você vê no céu||nuvem,sol,lua,estrela,avião,pássaro,arco-íris,balão,cometa,satélite,helicóptero,drone,pipa,raio,relâmpago,trovão,urubu,gavião,passarinho,borboleta,planeta,eclipse,aurora boreal,estrela cadente,meteoro,fogos de artifício,fumaça,pôr do sol,nascer do sol,céu azul,constelação,via láctea,estação espacial,paraquedas,ovni,disco voador,nevoeiro,névoa,chuva,neve,granizo,poluição,anjos,deus,ave,morcego,mosquito
Um tipo de árvore||mangueira,pinheiro,carvalho,ipê,eucalipto,jabuticabeira,palmeira,araucária,goiabeira,laranjeira,limoeiro,macieira,bananeira,coqueiro,jaqueira,cajueiro,abacateiro,figueira,oliveira,cerejeira,castanheira,seringueira,pau-brasil,baobá,sequoia,salgueiro,cedro,mogno,jacarandá,pitangueira,amendoeira,flamboyant,acácia,bambu,cipreste,álamo,bétula,plátano,abeto,faia,freixo,olmo,tamarindo,paineira,sibipiruna,quaresmeira,aroeira,jatobá,peroba,imbuia
Uma sobremesa gelada||sorvete,picolé,milk-shake,açaí,sundae,gelato,pavê,mousse,sorvete de creme,sorvete de chocolate,gelatina,pudim gelado,torta gelada,bolo gelado,sorvete de morango,sorvete de baunilha,sorvete de flocos,casquinha,paleta mexicana,raspadinha,sorvete de massa,sorvete de pote,frozen yogurt,cheesecake,tiramisu,petit gateau,mousse de maracujá,mousse de chocolate,pavê de chocolate,torta de limão,sorvete de limão,picolé de limão,picolé de chocolate,picolé de morango,bolo de sorvete,banana split,affogato,semifreddo,sorbet,sorvete de coco,açaí na tigela,sacolé,geladinho,chup-chup,dindin,gelo,crepe gelado,cone,sorvete de pistache
Um cômodo da casa||sala,cozinha,quarto,banheiro,garagem,varanda,escritório,lavanderia,área de serviço,sala de estar,sala de jantar,corredor,quintal,jardim,sótão,porão,despensa,closet,suíte,terraço,hall,edícula,churrasqueira,piscina,biblioteca,sacada,lavabo,copa,adega,cozinha americana,sala de tv,quarto de hóspedes,quarto de criança,brinquedoteca,academia,área gourmet,entrada,escada,telhado,laje,cobertura,varandão,área,salão,estúdio,oficina,ateliê,cantinho,home office
Um lanche||pão de queijo,sanduíche,hambúrguer,coxinha,pastel,pizza,misto quente,salgadinho,sanduíche natural,cachorro-quente,bolacha,biscoito,bolo,suco,fruta,iogurte,torrada,tapioca,empada,esfiha,pão com manteiga,pão com ovo,pão francês,pão de forma,pão de batata,pão na chapa,x-burguer,x-salada,x-tudo,pipoca,batata frita,nuggets,wrap,tostex,bauru,joelho,enroladinho,quibe,risole,pão de mel,barra de cereal,cereal,leite,achocolatado,café,chá,granola,vitamina,mini pizza,mini hambúrguer,tortilla,sanduíche de presunto
Um objeto do banheiro||escova de dente,sabonete,toalha,chuveiro,pasta de dente,espelho,vaso,shampoo,papel higiênico,pia,condicionador,desodorante,pente,secador,barbeador,navalha,fio dental,cotonete,sabão,creme dental,tapete,box,banheira,bidê,descarga,ralo,torneira,lixeira,escova sanitária,perfume,esponja,bucha,saboneteira,porta-escova,cesto,cortina,balança,prateleira,armário,esmalte,algodão,hidratante,escova de cabelo,chapinha,absorvente,fralda,lenço,touca,roupão,chinelo
Algo que você ouve na rua||buzina,carro,música,pássaros,sirene,conversa,moto,cachorro,ônibus,vendedor ambulante,obra,britadeira,caminhão,sorveteiro,carro de som,gritos,passos,vento,chuva,criança,latido,sino,igreja,freio,motor,escapamento,apito,alarme,vizinho,rádio,pagode,sertanejo,funk,pregão,jornaleiro,garrafeiro,gás,gari,trem,avião,helicóptero,polícia,ambulância,tiro,fogos,trânsito,barulho,silêncio,grilos,sapos
Um esporte olímpico||natação,atletismo,ginástica,judô,vôlei,remo,esgrima,salto com vara,futebol,basquete,tênis,handebol,boxe,ciclismo,surfe,skate,vôlei de praia,rugby,golfe,hipismo,tiro com arco,tiro esportivo,levantamento de peso,luta livre,taekwondo,caratê,triatlo,pentatlo moderno,saltos ornamentais,nado sincronizado,polo aquático,canoagem,vela,badminton,tênis de mesa,hóquei,breaking,escalada,maratona,corrida,salto em distância,salto em altura,lançamento de dardo,arremesso de peso,decatlo,heptatlo,marcha atlética,ginástica rítmica,ginástica artística,trampolim
Um personagem de história infantil||chapeuzinho vermelho,cinderela,branca de neve,pinóquio,peter pan,rapunzel,bela adormecida,patinho feio,lobo mau,três porquinhos,joão e maria,gato de botas,bela e a fera,pequena sereia,aladdin,alice,alice no país das maravilhas,mogli,dumbo,bambi,pato donald,mickey,rei leão,sítio do picapau amarelo,emília,narizinho,pedrinho,saci,curupira,cuca,mula sem cabeça,boto,iara,peppa,pooh,ursinho pooh,tigrão,leitão,coelho branco,chapeleiro maluco,rainha de copas,fada madrinha,príncipe encantado,bruxa,dragão,gigante,anão,sete anões,pequeno príncipe,pollyanna,heidi
Uma fruta amarela||banana,limão,abacaxi,manga,maracujá,melão,mamão,caju,pera,maçã,carambola,caqui,jaca,cajá,umbu,pêssego,damasco,laranja,tangerina,mexerica,pomelo,toranja,limão siciliano,banana prata,banana da terra,banana maçã,banana nanica,maçã amarela,uva verde,bacuri,goiaba amarela,tomate amarelo,fruta do conde,mamão papaia,cupuaçu,fruta-pão,pitomba,ananás,lima,limão taiti,manga palmer,manga rosa,melão amarelo
Um animal selvagem||leão,tigre,elefante,onça,lobo,urso,girafa,zebra,macaco,rinoceronte,hipopótamo,leopardo,guepardo,jacaré,crocodilo,gorila,chimpanzé,hiena,javali,raposa,veado,cervo,búfalo,bisão,camelo,canguru,coala,panda,lince,puma,jaguar,tamanduá,capivara,anta,lobo-guará,tatu,preguiça,quati,gambá,cobra,jibóia,sucuri,urubu,águia,coruja,tubarão,orca,lontra,castor,alce
Um modo de pagar||dinheiro,cartão,pix,débito,crédito,boleto,cheque,transferência,cartão de crédito,cartão de débito,espécie,à vista,parcelado,carnê,ted,doc,paypal,mercado pago,picpay,apple pay,google pay,vale,vale-refeição,vale-alimentação,ticket,tíquete,crediário,fiado,escambo,troca,bitcoin,criptomoeda,carteira digital,nfc,aproximação,qr code,link de pagamento,débito automático,desconto,à prazo,cédula,moeda,notas,trocado,ouro,cartão pré-pago,pré-pago,cartão virtual,pagar depois,cheque pré-datado
Um filme||titanic,avatar,vingadores,shrek,rei leão,matrix,toy story,harry potter,frozen,homem-aranha,batman,star wars,senhor dos anéis,jurassic park,procurando nemo,carros,os incríveis,divertida mente,moana,encanto,coco,up,wall-e,ratatouille,tubarão,de volta para o futuro,forrest gump,gladiador,o poderoso chefão,pulp fiction,clube da luta,coringa,interestelar,a origem,cidade de deus,tropa de elite,central do brasil,minha mãe é uma peça,o auto da compadecida,velozes e furiosos,piratas do caribe,a bela e a fera,aladdin,cinderela,branca de neve,pocahontas,mulan,kung fu panda,madagascar,era do gelo,como treinar o seu dragão,minions,meu malvado favorito,barbie,oppenheimer
Uma palavra que lembra o mar||onda,areia,praia,sal,água,azul,peixe,barco,navio,maré,concha,espuma,oceano,baleia,golfinho,tubarão,pescador,pescaria,marinheiro,âncora,farol,vela,veleiro,jangada,caiçara,sereia,pirata,tesouro,corais,coral,mergulho,mergulhar,surfe,prancha,biquíni,sol,verão,férias,brisa,salgado,horizonte,profundo,profundidade,abismo,fundo,tempestade,naufrágio,náufrago,ilha,caranguejo,gaivota,alga
Um animal que começa com T|T|tigre,tubarão,tartaruga,tatu,tucano,touro,tamanduá,tilápia,tamanduá-bandeira,tarântula,texugo,tordo,traíra,truta,tuiuiú,tucunaré,tatuzinho,tartaruga marinha,tico-tico,tentilhão,teiú,tapir
Um animal que começa com S|S|sapo,serpente,sabiá,siri,sagui,salmão,suricato,sardinha,sucuri,sanguessuga,saracura,saíra,surubim,solitária,sapo-cururu,seriema,salamandra,sanhaço
Uma fruta que começa com A|A|abacaxi,abacate,acerola,amora,ameixa,açaí,atemoia,ata,araçá,abiu,abricó,ananás,avelã,amêndoa,azeitona,amora-preta
Uma cor que começa com A|A|azul,amarelo,alaranjado,areia,azul-marinho,anil,ametista,âmbar,azul-turquesa,azul-royal,azul-celeste,azul-claro,azul-escuro,amarelo-ouro,amarelo-claro,amarelo-limão,azeitona,ágata,alabastro,aquamarina,açafrão,abóbora,avermelhado,acinzentado,azulado,amarronzado,azul-petróleo,azul-bebê,azul-piscina,azul-cobalto,ardósia,alfazema
Um país que começa com C|C|canadá,china,chile,colômbia,cuba,croácia,costa rica,camarões,camboja,cazaquistão,catar,chade,chipre,coreia do sul,coreia do norte,costa do marfim,congo,cabo verde,comores
Um país que começa com I|I|itália,índia,inglaterra,irlanda,israel,irã,iraque,islândia,indonésia,iêmen,ilhas salomão,irlanda do norte,iugoslávia
Uma cidade que começa com R|R|rio de janeiro,recife,roma,ribeirão preto,rio branco,rio grande,reykjavik,rosário,rio verde,rondonópolis,resende,rio claro,rio das ostras,roterdã,riga,rabat,rimini,reims,rouen,rolândia
Um nome de mulher que começa com A|A|ana,amanda,alice,aline,adriana,andréa,alessandra,ágatha,ana clara,ana júlia,ana luiza,andressa,ângela,antônia,aurora,alana,alícia,amélia,analu,anita,aparecida,arlete,assunção,aurélia,aretha,alexandra
Um nome de homem que começa com R|R|rafael,ricardo,rodrigo,roberto,rogério,renato,ronaldo,rui,raul,ramon,renan,rian,rodolfo,ronaldinho,romário,reinaldo,ricky,robson,rômulo,raimundo,ruan,rubens,ruy,ronan,ruben,rhuan
Uma comida que começa com S|S|sopa,sushi,sanduíche,salada,sorvete,strogonoff,salsicha,salgado,sashimi,salmão,sardinha,sagu,sonho,suflê,salame,sobrecoxa,salpicão,sarapatel,sarrabulho,sopa de legumes,sopa de feijão,sopa de cebola,sopa de mandioca,sanduíche natural,spaghetti,shawarma,samosa,sukiyaki,sopa de ervilha,salsichão
Um objeto que começa com M|M|mesa,mochila,mouse,martelo,mala,microfone,moeda,mapa,mola,máquina,manta,microondas,mesa de centro,marcador,mesinha,maleta,mangueira,molde,muleta,mochila escolar,monitor,motor,mala de viagem,maçaneta,marreta,medalha,moldura,manequim,mastro,maracá,microscópio,metrônomo
Uma profissão que começa com E|E|engenheiro,enfermeiro,eletricista,empresário,escritor,estudante,empreiteiro,encanador,economista,editor,educador,empregada,entregador,estilista,esteticista,escultor,enfermeira,engenheira,estagiário,explorador,esportista,embaixador,examinador,escrivão,empreendedor,engraxate,entomólogo,estatístico,empregado,empacotador,enólogo
Algo da praia que começa com A|A|areia,água,alga,ambulante,âncora,anzol,arraia,água de coco,argola,arrecife,arrebentação,amendoim,açaí,acampamento,amigos,aventura,asa-delta,alegria,areia fina,areia branca,aloha,almofada,aquário,aluguel,areia molhada
Um esporte que começa com V|V|vôlei,vela,vôlei de praia,vale-tudo,velocidade,vôlei sentado,vaquejada,voo livre,vela olímpica,vela de competição,vôlei de areia,vovinam,vaulting,vôlei feminino,vôlei masculino
`;

export type Pergunta = {
  id: string;
  texto: string;
  letra: string | null;
  comuns: string[];
  /** categoria fechada: só vale resposta que pertence à lista (ou que outros jogadores já usaram) */
  fechada: boolean;
};

export type PerguntaPublica = { id: string; texto: string; letra: string | null };

function ler(texto: string, prefixo: string): Pergunta[] {
  return texto
    .trim()
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((linha, i) => {
      const [bruto, letra, comuns] = linha.split("|");
      return {
        id: prefixo + String(i + 1).padStart(3, "0"),
        texto: bruto.replace(/^!/, "").trim(),
        letra: (letra ?? "").trim() || null,
        comuns: (comuns ?? "").split(",").map((s) => s.trim()).filter(Boolean),
        fechada: bruto.startsWith("!"),
      };
    });
}

/** Perguntas do mergulho diário: categorias fechadas, com listas longas ordenadas por familiaridade. */
export const DIARIAS: Pergunta[] = ler(BANCO_NOVO, "n");
const ANTIGAS: Pergunta[] = ler(BANCO, "p");
/** Todas (o mergulho livre sorteia entre elas). */
export const PERGUNTAS: Pergunta[] = [...DIARIAS, ...ANTIGAS];

const USADAS = Math.floor(DIARIAS.length / 7) * 7;
const DIAS_POR_CICLO = USADAS / 7;

function mulberry32(semente: number) {
  let a = semente >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function permutacao(ciclo: number): number[] {
  const rnd = mulberry32(ciclo * 7919 + 20261008);
  const v = Array.from({ length: USADAS }, (_, i) => i);
  for (let i = v.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [v[i], v[j]] = [v[j], v[i]];
  }
  return v;
}

/** As 7 perguntas do dia (iguais para todo mundo). Sem repetir até o ciclo todo acabar. */
export function perguntasDoDia(numero: number): Pergunta[] {
  const n = Math.max(1, Math.floor(numero)) - 1;
  const ciclo = Math.floor(n / DIAS_POR_CICLO);
  const dentro = n % DIAS_POR_CICLO;
  return permutacao(ciclo)
    .slice(dentro * 7, dentro * 7 + 7)
    .map((i) => DIARIAS[i]);
}

export function perguntaPorId(id: string): Pergunta | undefined {
  return PERGUNTAS.find((p) => p.id === id);
}

export function publica(p: Pergunta): PerguntaPublica {
  return { id: p.id, texto: p.texto, letra: p.letra };
}
